spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
spring.datasource.url: jdbc:mysql://192.168.20.19:3306/devpub?characterEncoding=utf8
spring.datasource.username: skilluser
spring.datasource.password: testTEST667+667
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false

server:
  tomcat:
    max-swallow-size: -1
  error:
    include-message: always
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      max-request-size: 5MB
#      max-file-size: 10MB
blogTitle: DevPub
blogSubtitle: Рассказы разработчиков
blogPhone: +7 (812) 244-54-32
blogEmail: vkotov@vfemail.net
blogCopyright: Gh Ltd.
blogCopyrightfrom: 2021

blogCaptchaTimeout: 3600
blogAnnounceTextLimit: 150
blogCommentTextLength: 5
blogUploadImageSizeLimit: 3145728

blogImageDBPathFolder: resources\static\img
blogImageRealPathFolder: src\main\resources\static\img

blogAvatarHeight: 36
blogAvatarWidth: 36

