spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
#spring.datasource.url: jdbc:mysql://192.168.20.19:3306/devpub?characterEncoding=utf8&useSSL=false
spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://192.168.20.19:3306/devpub?characterEncoding=utf-8}

spring.datasource.username: skilluser
spring.datasource.password: testTEST667+667
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false
server.port: ${PORT:8080}

server.tomcat.max-swallow-size: -1
server.error.include-message: always

blogTitle: GhDevPub
blogSubtitle: Рассказы разработчиков
blogPhone: +7 (812) 244-54-32
blogEmail: vkotov@vfemail.net
blogCopyright: Gh Ltd.
blogCopyrightfrom: 2020

blogCaptchaTimeout: 3600
blogAnnounceTextLimit: 150
blogCommentTextLength: 5
blogUploadImageSizeLimit: 3145728

blogUrl: https://devpub-gh4biz.herokuapp.com
blogImageDBPathFolder: resources/static/img/
blogImageRealPathFolder: src\main\resources\static\img\

blogAvatarHeight: 105
blogAvatarWidth: 100

blogEmailUser: noreplydevpub@gh4biz.ru
blogEmailPassword: 76Ye%uk6
